export const ApiControllers = {
    withdraw: "Withdraw/",
    transaction: "Transactions/",
    buySell: "Buysell/",
    master: "Master/",
    member: "Member/",
    swap: "Swap/",
    depositWithdraw: "DepositeWithdraw/",
    addressbook: "addressbook/",
    deposit: "Deposit/",
    admin: "Admin/",
    buy: "Buy/",
    sell: "Sell/",
    customers: "Customers/",
    markets: "Markets/",
    wallets: "Wallets/",
    notifications: "Notifications/",
    documents: "Documents/",
    dashboard: "Dashboard/",
    massPayment: "MassPayment/",
    common: "Common/",
    earn: "Earn/",
    partner:"Partner/"
}