const _config = {
    REACT_APP_API_END_POINT: process.env.REACT_APP_API_END_POINT,
    REACT_APP_REDIRECT_URI: process.env.REACT_APP_REDIRECT_URI,
    REACT_APP_CLIENT_ID: process.env.REACT_APP_CLIENT_ID,
    REACT_APP_AUTHORITY: process.env.REACT_APP_AUTHORITY,
    REACT_APP_SUMSUB_URI: process.env.REACT_APP_SUMSUB_URI,
    REACT_APP_COIN_GECO_API: process.env.REACT_APP_COIN_GECO_API,
    REACT_APP_WEB_URL: process.env.REACT_APP_WEB_URL,
    REACT_APP_GRID_API: process.env.REACT_APP_GRID_API,
    REACT_APP_UPLOAD_API: process.env.REACT_APP_UPLOAD_API,
    REACT_APP_APPLICATION_INSIGHTS_KEY: process.env.REACT_APP_APPLICATION_INSIGHTS_KEY,
    REACT_APP_ADMIN_URL: process.env.REACT_APP_ADMIN_URL,
    REACT_APP_IPREGISTERY_URL: process.env.REACT_APP_IPREGISTERY_URL,
    REACT_APP_IPREGISTERY_KEY: process.env.REACT_APP_IPREGISTERY_KEY,
    REACT_APP_SILENT_REDIRECT_URI: process.env.REACT_APP_SILENT_REDIRECT_URI,
    REACT_APP_NOTIFICATION_HUB: process.env.REACT_APP_NOTIFICATION_HUB,
    REACT_APP_ZOHO_WIDGET_URL: process.env.REACT_APP_ZOHO_WIDGET_URL,
    REACT_APP_ZOHO_WIDGET_CODE: process.env.REACT_APP_ZOHO_WIDGET_CODE,
    REACT_APP_CARDS_URL: process.env.REACT_APP_CARDS_URL,
    REACT_APP_ISSHOWCARDS: process.env.REACT_APP_ISSHOWCARDS,
    REACT_APP_BANK_UI_URL: process.env.REACT_APP_BANK_UI_URL,
    REACT_APP_BANKAPI_END_POINT: process.env.REACT_APP_BANKAPI_END_POINT,
    REACT_APP_SUBDOMAIN: process.env.REACT_APP_SUBDOMAIN
}
const AppConfig = process.env.NODE_ENV === "production"?window.AppConfig:_config;
export default AppConfig